### ISSUE TITLE
Failed to activate the move-by-paragraph package

### ISSUE THREAD

**Issue by natew** [karlin/move-by-paragraph#6]
Installing on new machine

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [move-by-paragraph](https://github.com/karlin/move-by-paragraph) package, v1.1.0
### Stack Trace

Failed to activate the move-by-paragraph package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/nw/.atom/packages/move-by-paragraph/lib/move-by-paragraph.coffee:6:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:499:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:494:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:478:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:686:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "audioBeep": false,
    "disabledPackages": [
      "background-tips"
    ],
    "packagesWithKeymapsDisabled": []
  }
}
```
### Installed Packages

``` coffee
# User
flint, v3.12.0
move-by-paragraph, v1.1.0

# Dev
No dev packages
```

**Comment by danlucraft** [comment]
Looks like this might be fixed on master. Just needs a new version publishing.
